alertmanager:
  enabled: false

server:
  enabled: true
  service:
    type: LoadBalancer
    nodePort: 30090
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "250m"

pushgateway:
  enabled: false

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false
