apiVersion: v1
kind: Service
metadata:
  name: order-postgres
spec:
  selector:
    app: order-postgres
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-postgres
  template:
    metadata:
      labels:
        app: order-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: orderdb
            - name: POSTGRES_USER
              value: orderuser
            - name: POSTGRES_PASSWORD
              value: orderpass
          ports:
            - containerPort: 5432
          args: ["-c", "max_connections=1000"]
